
version: '2'

services:                                                                      
 teamcity:
  restart: unless-stopped
  image: jetbrains/teamcity-server:latest
  volumes:
    - /srv/teamcity/data:/data/teamcity_server/datadir
    - /srv/teamcity/logs:/opt/teamcity/logs
  ports:
   - "8080:8111"

 teamcity_agent1:
  restart: unless-stopped
  image: jetbrains/teamcity-agent:latest
  links:
   - teamcity:teamcity
  volumes:
   - /srv/teamcity/agents/001/conf:/data/teamcity_agent/conf
  environment:
   - SERVER_URL=teamcity:8111
   - AGENT_NAME="tcagent_docker_v1_003"
